---
title: "Data Analysis"
output: github_document
date: "2025-06-17"
always_allow_html: true
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

```

## R Markdown

```{r Get data and load packages}
library(dplyr)
library(gprofiler2)
library(pheatmap)
library(ggplot2)
library(ggrepel)
library(sqldf)
library(limma)
library(dplyr)
library(tidyr)
library(gprofiler2)
library(PCAtools)
library(ggplotify)
library(gridExtra)
library(grid)

dat <- read.table("Processed_data.txt",  sep = "\t")
sample_info <- read.table("all_sample_info.txt",  sep = "\t")
```

```{r Select which samples will be used in the analysis}
# Filter for samples from negative HIV patients
negatives <- subset(sample_info, status == "HIV negative")

# Pick final samples from patients before they tested positive (for GSE195434 data)
selected_negs <- negatives %>%
  arrange(patient_id, time) %>%  # Order by patient id and time
  group_by(patient_id) %>%       # Group by patient id
  slice_max(order_by = time, n=1) %>%      #Select the last sample
  ungroup()                             # Remove Grouping

# Filter for samples from positive patients
positives <- subset(sample_info, status %in% c( "HIV-1 infected", "HIV-1 and HIV-2 dual infected", "HIV-2 infected"))

# Pick first samples from patients when they tested positive- and were treatment naive
selected_pos <- positives %>%
  arrange(patient_id, time) %>%    # Order by patient id and time
  group_by(patient_id) %>%        # Group by patient id
  slice_min(order_by = time, n =1) %>%  #Select the earliest sample
  ungroup()                             # Remove Grouping

# Combine negative and positive samples
selected_sample_info <-rbind(selected_negs, selected_pos) 

# Extract GEO accession numbers for selected samples
selected_samples <- selected_sample_info$geo_accession

# Subset the data to include only the selected samples
selected_data <- dat[,c(selected_samples)]
```

```{r Optional- select which samples will be used in the analysis using SQL}

# Select only the last pre infection and the first post infection sample taken from each patient in GSE195434
selected_negs <- sqldf("WITH negatives AS (
                      SELECT * 
                      FROM sample_info
                      WHERE status = 'HIV negative'
                    ),
                   ranked_samples AS( SELECT *,
                     ROW_NUMBER() OVER (PARTITION BY patient_id ORDER BY time DESC) as rn
                     FROM negatives
                   )
                   SELECT *
                   FROM ranked_samples
                   WHERE rn=1
                   ")

# Pick first samples from patients when they tested positive- and were treatment naive
selected_pos <- sqldf("WITH positives AS (
                      SELECT * 
                      FROM sample_info
                      WHERE NOT status ='HIV negative'
                    ),
                   ranked_samples AS( SELECT *,
                     ROW_NUMBER() OVER (PARTITION BY patient_id ORDER BY time ASC) as rn
                     FROM positives
                   )
                   SELECT *
                   FROM ranked_samples
                   WHERE rn=1
                   ")


# Combine selected negative and positive samples
selected_sample_info <- sqldf("SELECT * FROM selected_negs 
                              UNION
                              SELECT * FROM selected_pos
                              ")

# Extract GEO accession numbers for selected samples
selected_samples <- sqldf("SELECT geo_accession 
                          FROM selected_sample_info")

selected_samples <- selected_samples$geo_accession

# SQL does not support dynamic column selection so we use base R to index our columns of interest
selected_data <- dat[,c(selected_samples)]

```

```{r get a quick look at the distribution}
boxplot(selected_data)
```

```{r Label data by disease state and get mean expression values for each gene per disease state}
# Select the status column from the selected sample information
labels <- dplyr::select(selected_sample_info, status)

# Transpose the selected data and convert it to a dataframe
transposed_data <- data.frame(
  t(
    as.matrix(selected_data)
    )
  )

# Label the transposed data
labelled_data <- cbind(labels, transposed_data)

# Calculate mean values for each group
mean_values <- labelled_data %>%
  group_by(status) %>%
  dplyr::summarize(across(everything(), \(x) mean(x, na.rm = TRUE))) %>% # Compute mean for each column, remove any NAs
  tibble::column_to_rownames(var = "status") # Convert the status column to row names
```

```{r Analyze different groups using limma}

# Define groups based on disease status
groups <- factor(
  unique(labelled_data$status))

# Create a design matrix for linear modelling
design <- model.matrix(~status + 0, labelled_data)

# Clean column names and remove the 'status' prefix
colnames(design) <- make.names(colnames(design))
colnames(design) <- gsub("status", "", colnames(design))
colnames(design) <- factor(colnames(design), levels = colnames(design))

# Transpose the data for linear modeling and fit the model
t_labelled_data <- t(labelled_data[,-1])
fit <- lmFit(t_labelled_data, design)

# Set up contrasts of interest for comparison
coi <- c("HIV.1.infected-HIV.negative", "HIV.2.infected-HIV.negative", "HIV.1.and.HIV.2.dual.infected-HIV.negative")
contrasts <- makeContrasts(contrasts =coi,
                           levels = design)

# Recalculate model coefficients based on contrasts
fit2 <- contrasts.fit(fit, contrasts)

# Apply empirical Bayes statistics to the model
fit2 <- eBayes(fit2)

# Summarize and visualize results
results <- decideTests(fit2)

summary(results)
vennDiagram(results,
            cex = c(0.8, 1.0, 1.0))

# Get the adjusted p value for each coefficient
tT_HIV1 <- topTable(fit2, coef =1, adjust="BH", n = Inf)
tT_HIV2 <- topTable(fit2, coef =2, adjust="BH", n = Inf)
tT_dual <- topTable(fit2, coef =3, adjust="BH", n = Inf)

# Extract adjusted p values for each contrast
adj_p <- list()

for (contrast in coi) {
  topTable_results <- topTable(fit2,
                               coef = contrast,
                               n= Inf,
                               adjust = "BH")
  
  adj_p[[contrast]] <- data.frame(row.names = rownames(topTable_results), 
                                  adj.P.Val = topTable_results$adj.P.Val)
}
```


```{r Identify changes in gene expression then match with p values for each infection status}

# Transpose data frame of mean values
t_means <- data.frame(t(mean_values))

# Calculate the average fold change for HIV positive and negative samples for each gene
change <- t_means - t_means$HIV.negative

# Remove the HIV.negative column, as it is now zero
change <- data.frame(change[,-1]) 

# Merge adjusted p-values for all contrasts
adjusted_ps <- merge(adj_p[[1]], adj_p[[2]], by = "row.names") %>%
  tibble::column_to_rownames(var = "Row.names")

# Continue merging with the third set of p-values
adjusted_p_values <- data.frame(merge(adjusted_ps, adj_p[[3]], by = "row.names")) %>%
  tibble::column_to_rownames(var = "Row.names")

# Clean column names by removing '-HIV.negative'
colnames(adjusted_p_values) <- gsub("-HIV.negative", "",names(adj_p))

#Save the adjusted p-values table to a file
write.table(adjusted_p_values, "adjusted_p_values.txt", row.names= TRUE, quote= FALSE, sep="\t")

# Create data frame with fold change and adjusted p-value data for each group of HIV infected samples

# Check if row names are identical, if they are combine the columns
if (identical(rownames(change), rownames(adjusted_p_values))) {
  dual <- data.frame(Change = change$HIV.1.and.HIV.2.dual.infected, pvalue = adjusted_p_values$HIV.1.and.HIV.2.dual.infected, 
                     row.names = rownames(change))
  HIV1 <- data.frame(Change = change$HIV.1.infected, pvalue = adjusted_p_values$HIV.1.infected, 
                     row.names = rownames(change))
  HIV2 <- data.frame(Change = change$HIV.2.infected, pvalue = adjusted_p_values$HIV.2.infected, 
                     row.names = rownames(change))
} else {
  # If they don't match then order them accordingly
  change <- change[order(row.names(adjusted_p_values)),]
  
  dual <- data.frame(Change = change$HIV.1.and.HIV.2.dual.infected, pvalue = adjusted_p_values$HIV.1.and.HIV.2.dual.infected, 
                     row.names = rownames(change))
  HIV1 <- data.frame(Change = change$HIV.1.infected, pvalue = adjusted_p_values$HIV.1.infected, 
                     row.names = rownames(change))
  HIV2 <- data.frame(Change = change$HIV.2.infected, pvalue = adjusted_p_values$HIV.2.infected, 
                     row.names = rownames(change))
}

# Store datasets in a list
datasets <- list()
datasets[["HIV1"]] <- HIV1
datasets[["HIV2"]] <- HIV2
datasets[["Dual Infected"]] <- dual

# Plot each condition for a quick examination
for (i in 1:length(datasets)){
  dat <- datasets[[i]] 
  dat <- dat %>% 
    mutate(Significant = pvalue < 0.05) 
  
  # Add labels genes with the lowest 20 p values, and most significant changes in expression
  p_labels <- rownames(dat[order(dat$pvalue),])[1:20]
  fold_labels <- rownames(dat[order(-abs(dat$Change)),])[1:20]
  
  dat$gene <- rownames(dat)
  dat <- dat %>%
    mutate(PLabel = ifelse(gene %in% p_labels, gene, "")) %>%
    mutate(CLabel = ifelse(gene %in% fold_labels, gene, ""))
  
  plot1 <- ggplot(data = dat, mapping = aes(x = Change, y = -log10(pvalue), label = PLabel, col =  Significant)) +
    geom_point() +
    labs(title = paste(names(datasets)[i], "Genes with Statistically Significant Differential Expression" ), y = "-log10(adjusted p value)", x = "log2 difference") +
    theme(plot.title = element_text(hjust = 0.5))+
    geom_text_repel(col="black")
  
  plot2 <- ggplot(data = dat, mapping = aes(x = Change, y = -log10(pvalue), label = CLabel, col =  Significant)) +
    geom_point() +
    labs(title = paste(names(datasets)[i], "Most Differentially Expressed Genes" ), y = "-log10(adjusted p value)", x = "log2 difference") +
    theme(plot.title = element_text(hjust = 0.5))+
    geom_text_repel(col="black")
    
  print(plot1)
  print(plot2)
}

# The HIV-2 Infected and Dual Infected conditions only have 1 statistically significant gene in total likely due to low sample numbers. However, the HIV-1 infected samples are very interesting so we'll save those graphs

# Add labels genes with the lowest 20 p values, and most significant changes in expression
p_labels <- rownames(HIV1[order(HIV1$pvalue),])[1:20]
fold_labels <- rownames(HIV1[order(-abs(HIV1$Change)),])[1:20]
  
HIV1$gene <- rownames(HIV1)
HIV1 <- HIV1 %>%
  mutate(Significant = pvalue < 0.05) %>%
  mutate(PLabel = ifelse(gene %in% p_labels, gene, "")) %>%
  mutate(CLabel = ifelse(gene %in% fold_labels, gene, ""))

plot1 <- ggplot(data = HIV1, mapping = aes(x = Change, y = -log10(pvalue), label = PLabel, col =  Significant)) +
  geom_point() +
  labs(title = "Genes with the most statistically significant differential expression between \n HIV-1 infected and HIV negative individuals", y = "-log10(adjusted p value)", x = "log2 difference", color = "Statistically Significant (p < 0.05)")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_text_repel(col="black")
  
plot2 <- ggplot(data = HIV1, mapping = aes(x = Change, y = -log10(pvalue), label = CLabel, col =  Significant)) +
  geom_point() +
  labs(title = "Genes with the highest fold change between \n HIV-1 infected and HIV negative individuals", y = "-log10(adjusted p value)", x = "log2 difference", color = "Statistically Significant (p < 0.05)") +
  theme(plot.title = element_text(hjust = 0.5))+
  geom_text_repel(col="black")
    
print(plot1)
print(plot2)

# There was only one gene that had statistically significant differential expression for dual infection
dual$gene <- rownames(dual)
dual <- dual %>%
  mutate(Significant = pvalue < 0.05) %>%
  mutate(PLabel = ifelse(gene %in% c("TMEM119"), gene, ""))

# Show the plot
dual_infect_p <- ggplot(data = dual, mapping = aes(x = Change, y = -log10(pvalue), label = PLabel, col =  Significant)) +
  geom_point() +
  labs(title = "Differential expression between HIV negative \n and dual infected individuals", y = "-log10(adjusted p value)", x = "log2 difference", color = "Statistically Significant (p < 0.05)")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_text_repel(col="black")

# Make a new data frame for this graph, and substitute a new value for dual infected individuals
TMEM_data <- dplyr::select(labelled_data, status, TMEM119) 
TMEM_data$status <- gsub("HIV-1 and HIV-2 dual infected", "Dual infected", TMEM_data$status) 
TMEM_data$status <- factor(TMEM_data$status, levels = c(
    "HIV negative", "HIV-1 infected", "Dual infected", "HIV-2 infected"))

TMEM_plot <- ggplot(TMEM_data ,aes(x = status, y = TMEM119, group = status, fill = status)) +
  geom_dotplot(binaxis = "y", stackdir = "center", position = "dodge",dotsize = 1 ) +
  geom_boxplot()+
  labs(y = "TMEM119 log2 expression", x = NULL)

TMEM_plot

```

```{r}

# Filter genes based on statistical significance
sig_genes <- rownames(subset(adjusted_p_values,
              HIV.1.infected <= 0.05 | HIV.2.infected <= 0.05 | HIV.1.and.HIV.2.dual.infected <= 0.05))

# Filter genes based on change over 1.5x. Note that this data is log2 transformed and log2(1.5) is 0.6
changed_genes <- rownames(subset(change,
              abs(HIV.1.infected) >= 0.6 | abs(HIV.2.infected) >= 0.6 | abs(HIV.1.and.HIV.2.dual.infected) >= 0.6))

# Get a list of unique genes that met either statistical significance or gold change criteria
unique_genes <- unique(c(sig_genes, changed_genes))

# Ensure the rownames, aka GeneSymbols in your selected data is in the same format as the list of unique genes of interest
rownames(selected_data) <- make.names(rownames(selected_data))

# Select genes of interest from selected sample data
selected_genes <- selected_data[unique_genes,]

# Look at distribution of data in selected dataset
boxplot(selected_genes)
# Get relevant information for each sample
sample_groups <- dplyr::select(selected_sample_info, geo_accession, status, dataset) %>%
  tibble::column_to_rownames(var = "geo_accession")

# Specify colors for heatmap
my_colors <- list(
  status = c("HIV-1 infected" = "red", "HIV negative" = "green4", "HIV-1 and HIV-2 dual infected" = "purple", "HIV-2 infected" = "blue"),
             dataset = c(GSE195434 = "black", GSE200606 = "white")
  )

# First, look at samples and see if they are grouped by dataset or condition
corMat <- cor(selected_genes, use = "c")
corMat <- pheatmap(corMat,
                   annotation_col = sample_groups,
                   annotation_colors = my_colors,
                   show_rownames = FALSE,
                   show_colnames = FALSE,
                   main = "Correlation Between Samples")
                   #filename = "corMat.png")$gtable 

#ggsave("corMat.png",plot = corMat)
print(corMat)

# Now look at genes of interest, remove the dataset information from the annotation
sample_groups <- sample_groups[, !(names(sample_groups) %in%  c("dataset")), drop = FALSE]

# Convert data values to show difference from the mean
selected_genes_diff <- selected_genes - rowMeans(selected_genes)

all_genes <- pheatmap(selected_genes_diff, 
                      annotation_col = sample_groups,
                      annotation_colors = my_colors,
                      show_rownames = FALSE,
                      show_colnames = FALSE,
                      cutree_rows = 4,
                      cutree_cols = 5,
                      main = "Heatmap of Selected Genes")
                      #filename= "all_genes.png")$gtable
print(all_genes)

#ggsave("all_genes.png",plot = all_genes)
#grid.arrange(all_genes)
 
# What if we limit this to the top 10 genes?
top10 <- topTable(fit2, adjust = "BH")
top10_data <- selected_genes_diff[rownames(top10),]


top10_p <- pheatmap(top10_data, 
                    annotation_col = sample_groups,
                    annotation_colors = my_colors,
                    show_colnames = FALSE,
                    main = "10 most statistically significant genes")
                    #filename = "top10_pvalues.png")$gtable

print(top10_p)

#ggsave("top10_pvalues.png", top10_p)
#grid.arrange(top10_p)

# What if we limit this to the top 10 genes in regard to fold change?
change$max <- apply(change, 1, function(x) max(abs(x)))
change <- change[order(-change$max),]
top10_changed_genes <- change[1:10,]
top10_diff <- selected_genes_diff[rownames(top10_changed_genes),]

top10_diff <- pheatmap(top10_diff, 
                       annotation_col = sample_groups,
                       annotation_colors = my_colors,
                       show_colnames = FALSE,
                       main = "Top 10 genes with the highest fold changes")
                       #filename = "top10_fold_change.png")

print(top10_diff)
#ggsave("top10_fold_change.png", top10_diff)


# Select genes with a fold change > 1 and a statistically significant p value
genes_list <- list()
for (i in 1:length(datasets)){
  dat <- datasets[[i]]
  genes_to_add <- rownames(subset(dat,
              pvalue <= 0.05 & abs(Change) >= 1))
  genes_list <- c(genes_list, genes_to_add)
}

Sig_Change <- selected_genes_diff[unlist(genes_list),]
most_sig <- pheatmap(Sig_Change,
                     annotation_color = my_colors,
                     annotation_col = sample_groups,
                     show_colnames = FALSE,
                     main = "Genes with statistical signifcance and \n at least 1 fold change")
                     #filename = "Most_sig_genes.png")$gtable

print(most_sig)
#ggsave("Most_sig_genes.png", most_sig)


```
 

```{r PCA for genes with p value less than or equal to 0.05 and a 1 or greater fold change}

# Transpose data
PCA_data <- selected_genes[unlist(genes_list),]
  
pca_sample_groups <- sample_groups[colnames(selected_genes),, drop = FALSE]

# Add in a column to preserve the type of HIV infection, then simplify status to show if someone is positive or not
pca_sample_groups$type <- pca_sample_groups$status
pca_sample_groups$type <- gsub("HIV-1 infected", "HIV-1",
                            gsub("HIV-1 and HIV-2 dual infected", "HIV-1 and HIV-2",
                            gsub("HIV-2 infected","HIV-2",  pca_sample_groups$type)))

pca_sample_groups$status <- gsub("HIV-1 infected", "HIV positive",
                            gsub("HIV-1 and HIV-2 dual infected", "HIV positive",
                            gsub("HIV-2 infected","HIV positive",  pca_sample_groups$status)))

pca <- pca(PCA_data, metadata = pca_sample_groups, center = TRUE, scale = TRUE)

# Make a biplot with ellipses showing sample populations
biplot(pca, 
       colby = "status", colkey = c("HIV positive" = "#FC4E07", "HIV negative" ="#00AFBB"),
       shape = "type",
       ellipse = TRUE,
       ellipseType = 't',
       ellipseLevel = 0.95,
       ellipseFill = TRUE,
       ellipseAlpha = 1/4,
       ellipseLineSize = 0,
       legendPosition = 'right', legendLabSize = 10, legendIconSize = 3.0,
       lab = ""
       )

# Make a biplot that shows important loading info
biplot(pca, 
       colby = "status", colkey = c("HIV positive" = "#FC4E07", "HIV negative" = "#00AFBB"),
       shape = "type",
       showLoadings = TRUE,
       legendPosition = 'right', legendLabSize = 10, legendIconSize = 3.0,
       lab = ""
       )
# Use the elbow method to identify which PCs to keep
elbow <- findElbowPoint(pca$variance)

# Make a screeplot showing results of the elbow method, as well as which components explain 90% of variance
screeplot(pca,
          components = getComponents(pca, 1:20),
          hline = 90,
          vline = elbow)+
  annotate( "text",x = elbow + 2.5, y = 25,
                 label = "Elbow method", vjust = -1, size = 5)+
  annotate("text", x = 9, y = 80,
  label = "Explains 90% of variance", size = 5,
  )

# plot loadings
plotloadings(pca, caption = "Top 5% of variables")

plotloadings(pca,
  components = getComponents(pca, c(1:3)),
  drawConnectors = TRUE, labSize = 3, caption = "Top 5% of variables")

plotloadings(pca,
  components = getComponents(pca, c(1)),
  drawConnectors = TRUE, labSize = 3, caption = "Top 5% of variables") + coord_flip()

plotloadings(pca,
  components = getComponents(pca, c(2)),
  drawConnectors = TRUE, labSize = 3, caption = "Top 5% of variables") + coord_flip()

plotloadings(pca,
  components = getComponents(pca, c(3)),
  drawConnectors = TRUE, labSize = 3, caption = "Top 5% of variables") + coord_flip()

# Create a pairs plot
pairsplot(pca,
          components = getComponents(pca, 1:3),
          colby= "status", colkey = c("HIV positive" = "#FC4E07", "HIV negative" = "#00AFBB"))

```
```{r}
# Create a list the genes isolated from PCA
top <- list("EPSTI1", "IFI44", "IFI44L", "LY6E", "XAF1", "CD52", "EOMES", "GZMH", "IFI27", "HERC5", "IFIT1", "RSAD2", "NKG7")

# Select these genes from the data frame showing the differences in expression for each sample to the mean
top_data <- selected_genes_diff[unlist(top),]

# Create a heatmap
top_genes <- pheatmap(top_data,
                     annotation_color = my_colors,
                     annotation_col = sample_groups,
                     show_colnames = FALSE,
                     main = "Top Genes")
                     #filename = "top_pca_genes.png")$gtable


top_genes

#ggsave("top_pca_genes.png", top_genes)

#grid.arrange(top_genes)
```

```{r create graphs to show distribution for each gene of interest}
# Select these genes from the expression matrix
top_exprs <- labelled_data[,c(unlist(top), "status")]
# Assuming your data frame is named `df`, and the qualitative column is named `Qualitative`
columns <- names(top_exprs)[sapply(top_exprs, is.numeric)]

# Write functions to tell if a value is an outlier
findoutlier <- function(x) {
  return(x < quantile(x, .25) - 1.5*IQR(x) | x > quantile(x, .75) + 1.5*IQR(x))
}

# Clean up labels
top_exprs$status <- gsub("HIV-1 and HIV-2 dual infected", "Dual infected", top_exprs$status) 
top_exprs$status <- factor(top_exprs$status, levels = c(
    "HIV negative", "HIV-1 infected", "Dual infected", "HIV-2 infected"))

# Loop through each quantitative column and create a plot
for (col in columns) {
  # Select relevant data
  dat <- dplyr::select(top_exprs, col, status)%>%
    mutate(sample = row.names(top_exprs))
  # Make a dummy column, since mutate can't use variable names for columns
  dat$value <- dat[,1]
  # Identify outliers
  dat <- dat %>%
        group_by(status) %>%
        mutate(outlier = case_when(findoutlier(value) ~ sample))
  # Create plot
  p <- ggplot(dat, aes_string(x = 'status', y = col, color = 'status')) +
    geom_boxplot() +
    geom_point()+
    labs(title = paste(col, "Expression by Infection Status")) +
    theme(plot.title = element_text(hjust = 0.5))+
    geom_text(aes(label = outlier), na.rm = TRUE, hjust = -0.3, size = 3)+
    scale_color_manual(values = c("green4", "red", "purple", "blue"))
  
  print(p)
}

```


``` {r Functional Gene Enrichment}

# Perform functional enrichment analysis on list 
gost_info <- gost(query = unique_genes)

# This information can be used to enrich these genes for further pathway analysis
gostplot(gost_info)
results <- gost_info$result
order <- results[order(-results$intersection_size),]
```


